config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'indexes#index'

  # resources :indexes, only: [:show] do
  #   collection do
  #     get 'show', to: 'indexes#show'
  #   end
  # end

  resources :items, only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'purchase', to: 'items#purchase'
    end
    # routingにおけるcollectionとmemberの違いは生成するroutingに:idがつくかどうか
    # 参考URL：https://qiita.com/k152744/items/141345e34fc0095217fe
  end

  resources :credits, only: [:new, :show] do
    collection do
      post 'show', to: 'credits#show'
      post 'register', to: 'credits#register'
      post 'delete', to: 'credits#delete'
    end
    member do
      post 'buy', to: 'credits#buy'
    end
  end

  resources :users, only: [:show, :index] do
    collection do
      get 'index', to: 'users#index'
      get 'show', to: 'users#show'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/indexes/_footer.html.haml
.Under-img
  = image_tag src="/images/pict/bg-appBanner-pict.jpg", class: "Under-img__pict"
  .Under-img__in
    .Under-img__in--title
      だれでもかんたん、人生を変えるフリマアプリ
    .Under-img__in--text
      今すぐ無料ダウンロード！
    .Under-img__in--icon
      = link_to "#" do
        = image_tag src="/images/icon/appbtn.svg", class: "icon-app"
      = link_to "#" do
        = image_tag src="/images/icon/googlebtn.svg", class: "icon-google"
.Footer
  .Footer__left
    .Footer__left--title
      FURIMAについて
    .Footer__left--text
      = link_to "#", class: "footer-link" do
        %p 会社概要（運営会社）
      = link_to "#", class: "footer-link" do
        %p プライバシーポリシー
      = link_to "#", class: "footer-link" do
        %p FURIMA利用規約
      = link_to "#", class: "footer-link" do
        %p ポイントに関する特約
  .Footer__center
    .Footer__center--title
      FURIMAを見る
    .Footer__center--text
      = link_to "#", class: "footer-link" do
        %p カテゴリー一覧
      = link_to "#", class: "footer-link" do
        %p ブランド一覧
  .Footer__right
    .Footer__right--title
      ヘルプ＆ガイド
    .Footer__right--text
      = link_to "#", class: "footer-link" do
        %p FURIMAガイド
      = link_to "#", class: "footer-link" do
        %p FURIMAロゴ利用ガイドライン
      = link_to "#", class: "footer-link" do
        %p お知らせ
  .Footer__logo
    .Footer__logo--img
      = image_tag src="/images/logo/logo-white.png", class: "Footer__logo--img"
    .Footer__logo--text
      .Footer__logo--text__c ©️
      .Footer__logo--text__name FURIMA

app/views/indexes/_header.html.haml
.body-header
  .up
    .logo
      = link_to root_path do
        = image_tag src="/images/logo/logo.png", class: "logo__img"
    .Search-bar
      .Search-bar__inputBox
        = form_with url: search_items_path, method: :get, local: true do |f|
          = f.text_field :keyword, placeholder:"キーワードから探す",class:"Search-bar__inputBox--text"
          = button_tag type: 'submit', class: "Search-bar__inputBox--btn" do
            = icon('fas', 'search fa-lg',class: "Search-bar__inputBox--btn__icon")
  .under
    .Search-menu
      .Search-menu__category
        = link_to "#", class: "Search-menu__category--btn" do
          = image_tag src="/images/icon/icon_category.png", class: "Search-menu__category--btn__icon"
          %span<>
        = link_to "#", class: "Search-menu__category--text" do
          カテゴリーから探す
      .Search-menu__brand
        = link_to "#", class: "Search-menu__brand--btn" do
          = image_tag src="/images/icon/icon_brand.png", class: "Search-menu__brand--btn__icon"
          %span<>
        = link_to "#", class: "Search-menu__brand--text" do
          ブランドから探す
    .Btn
      - if user_signed_in?
        = button_to "ログアウト", destroy_user_session_path, method: :delete, class: "Btn__login logout-btn"
        = link_to "マイページ", users_path, class: "Btn__join"
      - else
        = link_to "ログイン", new_user_session_path, class: "Btn__login"
        = link_to "新規会員登録", new_user_registration_path, class: "Btn__join"

  .Exhibit
  = link_to new_item_path, class: "Exhibit" do
    .Exhibit__text 出品する
    .Exhibit__icon
      = image_tag src="/images/icon/icon_camera.png", class: "Exhibit__icon--pict"

app/views/indexes/_main.html.haml
.body-main
  .Top-img
    = image_tag src="/images/pict/bg-mainVisual-pict_pc.jpg", class: "Top-img__pict"
    .Top-img__in
      .Top-img__in--title
        人生を変えるフリマアプリ
      .Top-img__in--text
        %p FURIMAはだれでもかんたんに出品・購入ができる
        %p フリマアプリです
      .Top-img__in--icon
        = link_to "#" do
          = image_tag src="/images/icon/appbtn.svg", class: "icon-app"
        = link_to "#" do
          = image_tag src="/images/icon/googlebtn.svg", class: "icon-google"
  .Reason
    .Reason__top
      .Reason__top--text
        FURIMAが選ばれる3つの理由
      .Reason__top--ber
    .Reason__img
      .Reason__img--left
        = image_tag src="/images/pict/pict-reason-01.jpg", class: "Reason__img--left__pict"
        .Number
          .Number__one 1
      .Reason__img--center
        = image_tag src="/images/pict/pict-reason-02.jpg", class: "Reason__img--center__pict"
        .Number
          .Number__two 2
      .Reason__img--right
        = image_tag src="/images/pict/pict-reason-03.jpg", class: "Reason__img--right__pict"
        .Number
          .Number__three 3
    .Reason__title
      .Reason__title--boldleft
        .Reason__title--boldleft__color 3分
        .Reason__title--boldleft__black ですぐに出品
      .Reason__title--boldcenter
        .Reason__title--boldcenter__color シンプル
        .Reason__title--boldcenter__black で使いやすい
      .Reason__title--boldright
        .Reason__title--boldright__black 手数料
        .Reason__title--boldright__color 業界最安
    .Reason__text
      .Reason__text--left
        スマホで入力するだけで簡単に出品できる！
      .Reason__text--center
        めんどくさい入力は必要なく、検索も購入もスムーズ！
      .Reason__text--right
        10%でお得に出品&購入！
  .Center-img
    = image_tag src="/images/pict/bg-topMiddleDl-pict.jpg", class: "Center-img__pict"
    .Center-img__in
      .Center-img__in--title
        会員数日本一位
      .Center-img__in--text
        %p FURIMAは、フリマアプリで最も人気。
        %p 出品・購入回数も業界最多です！
        %p ほしかったあの商品に出会えるかもしれません
      .Center-img__in--icon
        = link_to "#" do
          = image_tag src="/images/icon/appbtn.svg", class: "icon-app"
        = link_to "#" do
          = image_tag src="/images/icon/googlebtn.svg", class: "icon-google"
  .Feature
    .Feature__top
      .Feature__top--text
        FURIMAの特徴
      .Feature__top--ber
    .Feature__img
      .Feature__img--left
        = image_tag src="/images/icon/icon-01.png", class: "Feature__img--left__pict"
      .Feature__img--center
        = image_tag src="/images/icon/icon-03.png", class: "Feature__img--center__pict"
      .Feature__img--right
        = image_tag src="/images/icon/icon-04.png", class: "Feature__img--right__pict"
    .Feature__title
      .Feature__title--left
        簡単に売り買いできる
      .Feature__title--center
        売り上げは即日振込みに対応
      .Feature__title--right
        様々な支払いに対応
    .Feature__text
      .Feature__text--left
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .Feature__text--center
        午前9時までに振込みを依頼いただければ、翌日に指定の口座に入金いたします！
      .Feature__text--right
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

app/views/indexes/_pickup.html.haml
.PickCategory
  .PickupCategory__text
    .PickCategory__text--title
      ピックアップカテゴリー
    .PickCategory__text--new
      = link_to "#", class: "PickCategory__text--new" do
        新規投稿商品
  .PickCategory__img
    - @items.each do |item|
      = link_to item_path(item.id) do
        .PickCategory__img--new
          = image_tag item.images[0].name.url, class: "PickCategory__img--new__images"
          - if item.deal_state_id == 1  # 商品が購入済み（deal_state_idが1）の場合のみSOLDマークを表示
            .sold-out
              .sold-out__text
                SOLD
          .main-Label
            .main-Label__text
              .main-Label__text--name
                = item.name
              .main-Label__text--price
                = "#{item.price}円"
              .main-Label__text--tax （税込）
// カテゴリー別新規投稿の表示（追加実装時にコメントアウトを取る）
.PickBrand
//  .PickBrand__text
//    .PickBrand__text--title
//      ピックアップブランド
//    .PickBrand__text--arc
//      = link_to "#", class: "PickBrand__text--arc" do
//        アーカイバ
//  .PickBrand__img
//    .PickBrand__img--new
//      .PickBrand__img--new__images
//      .main-Label-arc
//        .main-Label-arc__text
//          .main-Label-arc__text--name 商品名
//          .main-Label-arc__text--price お値段円
//          .main-Label-arc__text--tax （税込）

app/views/indexes/index.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "pickup"
  = render "footer"

app/views/indexes/show.html.haml
-# - breadcrumb :mypage
-# = render "layouts/breadcrumbs"

-# -# if:クレジットカード情報が登録されていなければ実行、else:クレジットカード情報が登録されていれば実行
-# = current_user.nick_name
-# さんのマイページ
-# -if ::Credit.where(user_id: current_user.id).exists?
-#   = form_tag(controller: :credits, action: :show, method: :post) do
-#     %button クレジットカードを削除する
-#   = link_to root_path, class: "aaa" do
-#     トップページに戻る
-# - else
-#   = form_tag(controller: :credits, action: :show, method: :post) do
-#     %button クレジットカードを登録する
-#   = link_to root_path, class: "aaa" do
-#     トップページに戻る