config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'indexes#index'

  # resources :indexes, only: [:show] do
  #   collection do
  #     get 'show', to: 'indexes#show'
  #   end
  # end

  resources :items, only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
      get 'purchase', to: 'items#purchase'
    end
    # routingにおけるcollectionとmemberの違いは生成するroutingに:idがつくかどうか
    # 参考URL：https://qiita.com/k152744/items/141345e34fc0095217fe
  end

  resources :credits, only: [:new, :show] do
    collection do
      post 'show', to: 'credits#show'
      post 'register', to: 'credits#register'
      post 'delete', to: 'credits#delete'
    end
    member do
      post 'buy', to: 'credits#buy'
    end
  end

  resources :users, only: [:show, :index] do
    collection do
      get 'index', to: 'users#index'
      get 'show', to: 'users#show'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :images

  def self.search(search)
    if search != ""
      Item.where('name LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :state
  belongs_to_active_hash :postage
  belongs_to_active_hash :day
  belongs_to_active_hash :prefecture
  accepts_nested_attributes_for :images
  # 複数モデルへの同時保存の際にバリデーションを設定
  validates_associated :images
  with_options presence: true do
    validates :name, length: { maximum: 40}
    validates :description, length: { maximum: 1000}
    validates :category_id
    validates :state_id
    validates :postage_id
    validates :prefecture_id
    validates :day_id
    validates :price
    validates :images
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index ,:search]
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def purchase
    @item = Item.find(params[:id])
    @address = Address.find(current_user.id)
  end

  def show
    @categories = Category.roots
    @category_id = @item.category_id
    @category_parent = Category.find(@category_id).parent.parent
    @category_child = Category.find(@category_id).parent
    @category_grandchild = Category.find(@category_id)
  end

  def new 
    @item = Item.new
    @item.images.build
    # データベースから親カテゴリーのみ抽出し、配列化
    @category_parent = Category.where(ancestry: nil)
  end

  def category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def create
    @item = Item.new(item_params)
    @item.update(deal_state_id: 0)  # 出品ページで値が入力されないdeal_state_idの値をここで代入しておく必要がある
    if @item.valid?
      @item.save
      redirect_to root_path, notice: '商品が投稿されました'
    else
      @category_parent = Category.where(ancestry: nil)
      render :new
    end
  end

  #------------------------
  # editアクション
  # 商品情報の編集
  # 商品情報編集機能実装時に追加
  #------------------------
  def edit
    @images = Image.where(item_id: params[:id])
    # ログインユーザが出品した商品かつ未購入状態の商品であればif文に内包された処理を実行
    if @item.user_id == current_user.id and @item.deal_state_id == 0
      # 該当商品の孫・子・親カテゴリーを変数へ代入
      # binding.pryして確認した格納データイメージは下記のとおり
      # 例えば、parentの中身を覗くと・・・
      # => #<Category:0x00007f9121f93620 id: 984, name: "スポーツ・レジャー", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:49 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:49 UTC +00:00>
      grandchild = Category.find(@item.category_id)   # 孫カテゴリーを代入
      child = grandchild.parent                       # 子カテゴリーを代入
      parent = child.parent                           # 親カテゴリーを代入

      # ビューのf.select_collectionの”selected”用
      # 編集画面遷移時にすでに登録されているカテゴリーの情報をセレクトボックスに表示するために利用
      # 親カテゴリーのnameとidを配列へ代入
      # binding.pryして確認した格納データイメージは下記のとおり
      # 例えば、@parent_arrayの中身を覗くと・・・
      # => ["スポーツ・レジャー", 984]
      @parent_array = []                              # 親カテゴリー配列を宣言
      @parent_array << parent.name                    # 親カテゴリー配列に親カテゴリーのnameカラムの値を代入
      @parent_array << parent.id                      # 親カテゴリー配列に親カテゴリーのidカラムの値を代入
      # 子カテゴリーのnameとidを配列代入
      @child_array = []
      @child_array << child.name
      @child_array << child.id
      # 孫カテゴリーのnameとidを配列代入
      @grandchild_array = []
      @grandchild_array << grandchild.name
      @grandchild_array << grandchild.id

      # ビューのf.select_collectionにカテゴリーの一覧を表示するために利用
      # binding.pryして確認した格納データイメージは下記のとおり
      # 例えば、@category_parent_arrayの中身を覗くと・・・
      #=> [#<Category:0x00007f9124d85ab0 id: 1, name: "レディース", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:43 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:43 UTC +00:00>,
        #<Category:0x00007f9124d859e8 id: 200, name: "メンズ", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:44 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:44 UTC +00:00>,
        #<Category:0x00007f9124d85880 id: 346, name: "ベビー・キッズ", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:45 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:45 UTC +00:00>,
        #<Category:0x00007f9124d857b8 id: 481, name: "インテリア・住まい・小物", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:46 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:46 UTC +00:00>,
        #<Category:0x00007f9124d856f0 id: 625, name: "本・音楽・ゲーム", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:47 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:47 UTC +00:00>,
        #<Category:0x00007f9124d85628 id: 685, name: "おもちゃ・ホビー・グッズ", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:47 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:47 UTC +00:00>,
        #<Category:0x00007f9124d85560 id: 798, name: "コスメ・香水・美容", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:48 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:48 UTC +00:00>,
        #<Category:0x00007f9124d85498 id: 898, name: "家電・スマホ・カメラ", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:49 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:49 UTC +00:00>,
        #<Category:0x00007f9124d853d0 id: 984, name: "スポーツ・レジャー", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:49 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:49 UTC +00:00>,
        #<Category:0x00007f9124d85308 id: 1093, name: "ハンドメイド", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:50 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:50 UTC +00:00>,
        #<Category:0x00007f9124d85240 id: 1147, name: "チケット", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:50 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:50 UTC +00:00>,
        #<Category:0x00007f9124d85100 id: 1207, name: "自動車・オートバイ", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:50 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:50 UTC +00:00>,
        #<Category:0x00007f9124d85038 id: 1270, name: "その他", ancestry: nil, created_at: Sun, 14 Feb 2021 07:49:51 UTC +00:00, updated_at: Sun, 14 Feb 2021 07:49:51 UTC +00:00>]
      # 親カテゴリーを全てインスタンス変数へ代入
      @category_parent_array = Category.where(ancestry: nil)
      # 子カテゴリーを全てインスタンス変数へ代入
      @category_children_array = Category.where(ancestry: child.ancestry)
      # 孫カテゴリーを全てインスタンス変数へ代入
      @category_grandchildren_array = Category.where(ancestry: grandchild.ancestry)
    
    # ログインユーザが出品した商品でない場合もしくは商品が購入済みの状態であればelse文に内包された処理を実行
    else
      flash[:alert] = 'すでに購入された商品かあなたが出品者の商品ではないため商品情報の編集はできません。'     # 商品情報を編集できない旨をフラッシュメッセージで表示
      redirect_to item_path                                                                      # 商品詳細ページにリダイレクト
    end
  end

  #-----------------------------
  # updateアクション
  # 商品情報の編集内容をDBに反映させる
  # 商品情報編集機能実装時に追加
  #-----------------------------
  def update
    if @item.valid?
      @item.update(item_params)                     # 商品情報を更新
      flash[:notice] = '商品情報の編集が完了しました。'  # 商品情報を編集できた旨をフラッシュメッセージで表示
      redirect_to item_path(@item)                  # 商品詳細ページにリダイレクト
    else
      @images = Image.where(item_id: params[:id])
      flash[:notice] = '商品情報の編集に失敗しました。'  # 商品情報の編集に失敗した旨をフラッシュメッセージで表示
      render :edit                                  # 商品情報編集画面にレンダー
    end
    # redirect_toとrenderの違い
    # 参考URL：https://qiita.com/morikuma709/items/e9146465df2d8a094d78
  end

  def search
    @items = Item.search(params[:keyword])
  end

  def destroy
    if @item.user_id == current_user.id
       @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  # 出品時のデータをDBに送るストロングパラメーター
  private
  def item_params
    params.require(:item).permit(:name,:description,:brand,:state_id,:postage_id,:prefecture_id,:day_id,:price,:category_id, images_attributes: [:name, :id]).merge(user_id: current_user.id)
  end

  def address_params
    params.require(:address).permit(:postcode,:prefecture_id,:city,:block,:building,:phone_number,:user_id).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item-main.html.haml
.body
  .Top-bar
    .Top-bar__text
      - breadcrumb :item
      = render "layouts/breadcrumbs"   
  .Item
    .Item__title
      = @item.name
    = image_tag @item.images[0].name.url, class: "Item__img"
    .Item__little
      = image_tag @item.images[0].name.url, class: "Item__little--1"
      .Item__little--2
      .Item__little--3
      .Item__little--4
    .Item__price
      ￥
      = @item.price
    .Item__tax 
      = @item.postage.name
    -if user_signed_in? && current_user.id == @item.user_id
      = link_to edit_item_path,class: "Buy-btn__edit" do
        .Buy-btn__text 商品を編集する
      = link_to @item, method: :delete ,class: "Buy-btn__delete" do
        .Buy-btn__text 商品を削除する
    -else
      = link_to purchase_item_path,class: "Buy-btn" do
        .Buy-btn__text 購入画面へ進む
    .Item__text
      = @item.description
    %table.Table
      %tr
        %th.Table__title 出品者
        %td
          = link_to "#{@item.user.nick_name}", "#", class: "color"
      %tr
        %th{rowspan: "1", class: "Table__title"} カテゴリー
        %td.category.category-top
          = link_to "#{@category_parent.name}", "#", class: "color"
        %td.category
          = link_to "#{@category_child.name}", "#", class: "color"
        %td.category.category-bottom
          = link_to "#{@category_grandchild.name}", "#", class: "color"
      %tr
        %th.Table__title ブランド
        %td
          .Table__text
            = @item.brand
      %tr
        %th.Table__title 商品の状態
        %td
          .Table__text
            = @item.state.name
      %tr
        %th.Table__title 発送料の負担
        %td
          .Table__text
            = @item.postage.name
      %tr
        %th.Table__title 発送元の地域
        %td
          .Table__text
            = @item.prefecture.name
      %tr
        %th.Table__title 発送の目安
        %td
          .Table__text
            = @item.day.name
    .Item__btn
      .Item__btn--favorite
        = icon('fas', 'star', class: "star-icon")
        お気に入り
        .count 0
      .Item__btn--report
        = icon('fas', 'flag', class: "flag-icon")
        不適切な商品の通報
  .Comment
    = form_with html: {class: "form"} do |f|
      = f.text_area :comment, class: "Comment__form"
    .Comment__text
      %p 相手のことを考え丁寧なコメントを心がけましょう。
      %p 不快な言葉遣いなどは利用制限や退会処分となることがあります。
    = form_with html: {class: "form-btn"} do |f|
      =icon('fas', 'comment', class: "comment-icon")
      = f.submit "コメントする", class: "comment-btn"
  .Others
    .Others__title #{@item.user.nick_name}さんのその他の出品
    .Others__img
      .Others__img--new
        .Label
          .Label__name 商品名
          .Label__price お値段円
          .Label__tax （税込）
      .Others__img--new
      .Others__img--new
      .Others__img--new
    .Category #{@category_grandchild.name}（#{@category_parent.name}）その他の商品
    .Category__img
      .Category__img--new
        .Label
          .Label__name 商品名
          .Label__price お値段円
          .Label__tax （税込）
      .Category__img--new
      .Category__img--new
      .Category__img--new

app/views/items/_items-show-footer.html.haml
//商品購入確認ページのフッター
.AccountPage__footer
  .AccountPage__footer--btn
    = link_to "プライバシーポリシー","#"
    = link_to "フリマ利用規約","#"
    = link_to "特定商取引に関する表記","#"
    = link_to image_tag("/images/logo/logo-white.png", class:"logo-footer"),root_path
    %p.buttom ©FURIMA

app/views/items/_items-show-header.html.haml
//商品購入確認ページのヘッダー
.top
  = link_to image_tag( '/images/logo/logo.png',class:"logo"),root_path 

app/views/items/_login.html.haml
.LoginPage
  .LoginPage__header
    = link_to image_tag src="/assets/logo.png", size: "185x50"
  
  .LoginPage__body
    .LoginPage__body__top
      .LoginPage__body__top__content
        %p.LoginPage__body__top__content__text
          アカウントをお持ちでない方はこちら
        %a.LoginPage__body__top__content__registration-link{ href: '#' }
          新規会員登録

    .LoginPage__body__middle
      .LoginPage__body-middle__content
        = button_to '仮：Googleでログイン'
        = button_to '仮：Facebookでログイン'
        = button_to '仮：Appleでログイン'

    .LoginPage__body__bottom
      .LoginPage__body__bottom__content
        .LoginPage__body__bottom__content__form
          %div.LoginPage__body__bottom__content__form__email
            %input.LoginPage__body__bottom__content__form__email__text-form{type: "text", placeholder: "　メールアドレス"}
          %div.LoginPage__body__bottom__content__form__password
            %input.LoginPage__body__bottom__content__form__password__text-form{type: "text", placeholder: "　パスワード"}
          //= email_field :user, :address, class: "email" こっちの方が良い？？
          //= password_field_tag :password, "#", class: "password" こっちの方が良い？
        = button_to "ログイン", "#", class: "LoginPage__body__bottom__content__login-btn"
        %a.LoginPage__body__bottom__content__link{ href: '#' }
          パスワードをお忘れの方
    
  .LoginPage__footer
    .LoginPage__footer__content
      .LoginPage__footer__content__link
        %a.LoginPage__footer__content__link__text1{ href: '#' }
          プライバシーポリシー
        %a.LoginPage__footer__content__link__text2{ href: '#' }
          フリマ利用規約
        %a.LoginPage__footer__content__link__text3{ href: '#' }
          特定商取引に関する表記
      .LoginPage__footer__content__logo
        = link_to image_tag src="/assets/logo.png", size: "185x50", class: "LoginPage__footer__content__logo__img"
        %p.LoginPage__footer__content__logo__text
          ©︎FURIMA

app/views/items/_p-c-footer.html.haml
//商品購入確認ページのフッター
.AccountPage__footer
  .AccountPage__footer--btn
    = link_to "プライバシーポリシー","#"
    = link_to "フリマ利用規約","#"
    = link_to "特定商取引に関する表記","#"
    = link_to image_tag("/images/logo/logo-white.png", class:"logo-footer"),root_path
    %p.buttom ©FURIMA

app/views/items/_p-c-header.html.haml
//商品購入確認ページのヘッダー
.top
  = link_to image_tag( '/images/logo/logo.png',class:"logo"),root_path 

app/views/items/edit.html.haml
.body
  .Top-logo
    = link_to "#" do
      = image_tag src="/images/logo/logo.png", class: "Top-logo__img"
  .Data
  = form_with model:@item, local: true do |f|
    .Image-space
      = render 'layouts/error_messages', model: f.object
      .Image-space__text
        .text 出品画像
        .label 必須
        //以下は追加実装時にコメントアウトを取る
        //.Image-space__detail 最大5枚までアップロードできます
      .Image-space__image
        現在の出品画像
        = f.fields_for :images do |image|
          = image_tag src= @images[0].name.url, size: "200x200"
     
      .Image-space__box
        = f.fields_for :images do |image|
          .Image-space__box--in
            出品画像を編集したい場合は画像ファイルを選択しなおしてください。
            = image.file_field :name

    .Item-new
      .Item-new__name
        .text 商品名
        .label 必須
      = f.text_field :name, placeholder: "40文字まで", maxlength: "40", class: "Item-new__input"
      .Item-new__detail
        .text 商品の説明
        .label 必須
      = f.text_area :description, placeholder: "商品の説明（必須1,000文字以内）\r\n（色、素材、重さ、定価、注意点など）\r\n\r\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", maxlength: "1000", class: "Item-new__form"
      .count 0/1000
    .Detail
      .Detail__category
        .text カテゴリー
        .label 必須
      .Detail__select-parent
      =f.collection_select :category_id, @category_parent_array, :id, :name, {selected: @parent_array},{class: "category-select", id: "select_category"}
      -# 下記クラス名をcategory.jsのfunction appendChildrenBoxの$('~').appendの~部分と一致させないと、親カテゴリー変更時に子カテゴリー選択用のセレクトボックスが出現しない
      .Detail__select-children
      =f.collection_select :category_id, @category_children_array, :id, :name, {selected: @child_array}, {class: "category-select", id: "child_category"}
      -# 下記クラス名をcategory.jsのfunction appendGrandchildrenBoxの$('~').appendの~部分と一致させないと、子カテゴリー変更時に孫カテゴリー選択用のセレクトボックスが出現しない
      .Detail__select-grandchildren
      =f.collection_select :category_id, @category_grandchildren_array, :id, :name, {selected: @grandchild_array}, {class: "category-select", id: "grandchild_category"}

      .Detail__brand
        .text ブランド
        .gray-label 任意
      = f.text_field :brand, placeholder: "例）シャネル", class: "Detail__input"
      .Detail__state
        .text 商品の状態
        .label 必須
      = f.collection_select :state_id, State.all, :id, :name,include_blank: "選択してください"
    .Sending
      .Sending__title
        %p 発送について
        = link_to "#" do
          =icon('far', 'question-circle', class: "question")
      .Sending__burden
        .text 発送料の負担
        .label 必須
      = f.collection_select :postage_id, Postage.all, :id, :name,include_blank: "選択してください"
      .Sending__area
        .text 発送元の地域
        .label 必須
      = f.collection_select :prefecture_id, Prefecture.all, :id, :name,include_blank: "選択してください"
      .Sending__days
        .text 発送までの日数
        .label 必須
      = f.collection_select :day_id, Day.all, :id, :name,include_blank: "選択してください"
    .Price
      .Price__title
        %p 価格
        .number （¥300〜9,999,999）
        = link_to "#" do
          =icon('far', 'question-circle', class: "question")
      .Price__set
        .Price__set--title
          .text 販売価格
          .label 必須
        .Price__set--value
          %p.mark ¥
          = f.number_field :price, value: @item.price, min: "300", max: "9999999", class: "Price__set--value__bar"
      .Price__fee
        .text
          %p 販売手数料
          .rate （10%）
        .display ー
      .Price__bar
      .Price__profit
        %p 販売利益
        .display ー
    .Under-menu
      .Btn-up
        = f.submit "商品情報を更新する", class: 'exhibit'
      .Btn-under
        = link_to "#", class: "save" do
          下書きに保存
      = link_to "#", class: "back" do
        もどる
    .Under-text
      .up
        %p 禁止されている
        = link_to "#", class: "color" do
          行為
        %p および
        = link_to "#", class: "color" do
          出品物
        %p を必ずご確認ください。
        = link_to "#", class: "color" do
          偽ブランド品
        %p や
        = link_to "#", class: "color" do
          盗品物
        %p などの販売は犯罪であり、法
      .under
        %p 律により処罰される可能性があります。 また、出品をもちまして
        = link_to "#", class: "color" do
          加盟店規約
        %p に同意したことになります。
  = render "items-show-footer"

app/views/items/index.html.haml
//商品購入確認ページのビューファイル
.AccountPage
  = render "items-show-header"

  .items-show-main
    .top
      購入内容の確認

    .middle-1 
      .middle-1__img
        = image_tag src="/images/icon/appbtn.svg", size: "80x80"
      .middle-1__texts
        .middle-1__texts--item-name
          = @item.name
        .middle-1__texts--prices
          .fee
            送料込み（税込み）
          .price
            ¥
            = @item.price

    .middle-2
      .middle-2__text
        支払い金額
      .middle-2__price
        ¥
        = @item.price

    .middle-3
      .middle-3__text
        支払い方法
        -# ログインしているユーザーのクレジットカードが登録されていれば実行
      - if ::Credit.where(user_id: current_user.id).exists?
        登録済みのクレジットカード
        -# ログインしているユーザーのクレジットカードが登録されていなければ実行（new_credit_path:クレジットカード登録画面へのパス）
      - else
        = link_to new_credit_path, class: "middle-3__link" do
          = icon('fa', 'plus-circle')
          登録してください。

    .middle-4
      .middle-4__top
        .middle-4__top--text
          配送先
        = link_to "#", class: "middle-4__top--link" do
          変更する>
      .middle-4__bottom
        .middle-4__bottom--postal-code
          = @address.postcode
        .middle-4__bottom--address
          = @address.prefecture_id
          = @address.city
          = @address.block
          = @address.building
        .middle-4__bottom--user-name
          = current_user.last_name
          = current_user.first_name

    .bottom
      .bottom__message
        -# クレジットカード情報が有りかつ商品未購入状態かつ商品の出品者がログインユーザでない時
      - if @item.deal_state_id == 0 && @item.id != current_user.id
        - if ::Credit.where(user_id: current_user.id).exists?
          = form_tag(controller: :credits, action: :buy, method: :post) do
            %button 購入
          -# クレジットカード情報が無いが、商品未購入状態かつ商品の出品者がログインユーザでない時
        - else
          クレジットカードを登録してください
      - else
        購入できません（誰かが購入済みの商品もしくはあなたが出品した商品です）

  = render "items-show-footer"

app/views/items/new.html.haml
.body
  .Top-logo
    = link_to "#" do
      = image_tag src="/images/logo/logo.png", class: "Top-logo__img"
  .Data
  = form_with model:@item, local: true do |f|
    .Image-space
      = render 'layouts/error_messages', model: f.object
      .Image-space__text
        .text 出品画像
        .label 必須
      //以下は追加実装時にコメントアウトを取る
      //.Image-space__detail 最大5枚までアップロードできます
      .Image-space__box
        = f.fields_for :images do |image|
          .Image-space__box--in
            = image.file_field :name
            -# =icon('fas', 'camera', class: "camera-icon")
            -# %p クリックしてファイルをアップロード
    .Item-new
      .Item-new__name
        .text 商品名
        .label 必須
      = f.text_field :name, placeholder: "40文字まで", maxlength: "40", class: "Item-new__input"
      .Item-new__detail
        .text 商品の説明
        .label 必須
      = f.text_area :description, placeholder: "商品の説明（必須1,000文字以内）\r\n（色、素材、重さ、定価、注意点など）\r\n\r\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", maxlength: "1000", class: "Item-new__form"
      .count 0/1000
    .Detail
      %p 商品の詳細
      .Detail__category
        .text カテゴリー
        .label 必須
      = f.collection_select :category, @category_parent, :id, :name, {prompt: "選択してください"}, {class: "category-select", id: "select_category"}
      .Detail__select-children
      .Detail__select-grandchildren
      .Detail__brand
        .text ブランド
        .gray-label 任意
      = f.text_field :brand, placeholder: "例）シャネル", class: "Detail__input"
      .Detail__state
        .text 商品の状態
        .label 必須
      = f.collection_select :state_id, State.all, :id, :name,include_blank: "選択してください"
    .Sending
      .Sending__title
        %p 発送について
        = link_to "#" do
          =icon('far', 'question-circle', class: "question")
      .Sending__burden
        .text 発送料の負担
        .label 必須
      = f.collection_select :postage_id, Postage.all, :id, :name,include_blank: "選択してください"
      .Sending__area
        .text 発送元の地域
        .label 必須
      = f.collection_select :prefecture_id, Prefecture.all, :id, :name,include_blank: "選択してください"
      .Sending__days
        .text 発送までの日数
        .label 必須
      = f.collection_select :day_id, Day.all, :id, :name,include_blank: "選択してください"
    .Price
      .Price__title
        %p 価格
        .number （¥300〜9,999,999）
        = link_to "#" do
          =icon('far', 'question-circle', class: "question")
      .Price__set
        .Price__set--title
          .text 販売価格
          .label 必須
        .Price__set--value
          %p.mark ¥
          = f.number_field :price, value: "0", min: "300", max: "9999999", class: "Price__set--value__bar"
      .Price__fee
        .text
          %p 販売手数料
          .rate （10%）
        .display ー
      .Price__bar
      .Price__profit
        %p 販売利益
        .display ー
    .Under-menu
      .Btn-up
        = f.submit "出品する", class: 'exhibit'
      .Btn-under
        = link_to "#", class: "save" do
          下書きに保存
      = link_to "#", class: "back" do
        もどる
    .Under-text
      .up
        %p 禁止されている
        = link_to "#", class: "color" do
          行為
        %p および
        = link_to "#", class: "color" do
          出品物
        %p を必ずご確認ください。
        = link_to "#", class: "color" do
          偽ブランド品
        %p や
        = link_to "#", class: "color" do
          盗品物
        %p などの販売は犯罪であり、法
      .under
        %p 律により処罰される可能性があります。 また、出品をもちまして
        = link_to "#", class: "color" do
          加盟店規約
        %p に同意したことになります。
  = render "items-show-footer"

app/views/items/show.html.haml
.wrapper
  = render "indexes/header"
  = render "item-main"
  = render "indexes/footer"